/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <Memory_Address.h>
#include <stdint.h>
#include <stdio.h>

void PinMode_Configuration(volatile unsigned int *port_add, int pin_no, GPIO_MODE MODE, unsigned char CNF)
{
	unsigned char value=0;

	SETBITS(value, 0, MODE);
	SETBITS(value, 2, CNF);

	CLEARBITS(*port_add, (pin_no%8)*4, 0xf);
	SETBITS(*port_add, (pin_no%8)*4, value);
}

void delay_sec(unsigned int delay)
{
	for(unsigned int i=0; i< (delay*8000000);i++);//External Clock frequency(onboard crystal) of STM32f103c8t6 is 8MHZ
	return;
}

int main(void)
{
	SETBIT(*RCC_APB2ENR,4);//As mentioned in PG_NO : 112(RCC) and 163(GIPO)
	PinMode_Configuration(GPIOC_CRH, 13, OUTPUT_MODE_2MHZ, GP_OP_PUSH_PULL);

	while(1)
	{
		TOGGLEBIT(*GPIOC_ODR,13);
		delay_sec(1);
	}
    return 0;
}


